spring:
  application:
    name: hystrix-turbine-dashboard

server:
  port: 9003

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
    - http://localhost:8761/eureka
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    healthcheck:
      enabled: true
  instance:
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream

turbine:
  cluster-name-expression: new String("default")
  app-config: api-resource,api-client