spring:
  application:
    name: api-resource

server:
  port: 9001

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    healthcheck:
      enabled: true
  instance:
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream

logging:
  level:
    org.springframework: INFO
    com.netflix.hystrix: DEBUG
    com.rest.example.apiresource: TRACE

---

spring:
  profiles: test
  discovery:
    enabled: false

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
